/**
 * 后端接口定义
 * 仅保留后端实际提供的接口。
 */
import request from '@/utils/request'
import type {
  AdminDailyTrendItem, AuthDailyTrendItem, AdminInfo, CarouselConfig, App, AppCategory, AppEndpoint, AppOrder, AppPlan, AppRealNameRecord, Article, Category, Comment, Tag, AppSubscription, EmailConfig, LoginForm, PageResponse, PaymentConfig, RealNameConfig, RegisterConfig, Result, SiteConfig, User, UserLoginResponse
} from '@/types'

function toUrlEncoded(data: object): URLSearchParams {
  const params = new URLSearchParams()
  Object.entries(data).forEach(([key, value]) => {
    if (value !== undefined && value !== null) params.append(key, String(value))
  })
  return params
}

export const publicApi = {
  getSiteInfo: () => request<Result<SiteConfig>>({ url: '/api/GetSiteConfigInfo', method: 'GET' }),
  getCarousels: () => request<Result<CarouselConfig[]>>({ url: '/api/carousel/list', method: 'GET' }),
  getRegisterInfo: () => request<Result<RegisterConfig>>({ url: '/api/register/info', method: 'GET' }),
  getPublicAntiBrushConfig: () => request<Result<Record<string, unknown>>>({ url: '/api/anti-brush/config', method: 'GET' }),
  getPublicAppCategories: () => request<Result<AppCategory[]>>({ url: '/api/app/category/list', method: 'GET' }),
  getPublicApps: () => request<Result<App[]>>({ url: '/api/app/list', method: 'GET' }),
  getPublicAppPlans: (app_id: number) => request<Result<AppPlan[]>>({ url: '/api/app/plan/list', method: 'GET', params: { app_id } }),
  getPublicAppEndpoints: (app_id: number) => request<Result<AppEndpoint[]>>({ url: '/api/app/endpoint/list', method: 'GET', params: { app_id } }),
  sendCode: (data: { email: string } & Record<string, unknown>) => request<Result>({ url: '/api/SendCode', method: 'POST', data: toUrlEncoded(data) }),
  verifyCode: (data: { email: string; code: string }) => request<Result>({ url: '/api/VerifyCode', method: 'POST', data: toUrlEncoded(data) }),
  sendPhoneCode: (data: { phone: string } & Record<string, unknown>) => request<Result>({ url: '/api/SendPhoneCode', method: 'POST', data: toUrlEncoded(data) }),
  getArticles: (params?: Record<string, unknown>) => request<Result<PageResponse<Article>>>({ url: '/api/article/list', method: 'GET', params }),
  getArticleDetail: (id: number) => request<Result<PageResponse<Article>>>({ url: '/api/article/list', method: 'GET', params: { id } }),
  getCategoryTree: () => request<Result<Category[]>>({ url: '/api/GetCategoryChildrenInfo', method: 'GET' }),
  getArticleAccess: (article_id: number) => request<Result>({ url: '/api/user/article/access', method: 'GET', params: { article_id } }),
  getComments: (params?: Record<string, unknown>) => request<Result<PageResponse<Comment>>>({ url: '/api/GetCommentInfo', method: 'GET', params }),
  createComment: (data: Record<string, unknown>) => request<Result>({ url: '/api/CreateComment', method: 'POST', data: toUrlEncoded(data) }),
  likeArticle: (article_id: number) => request<Result<{ liked: boolean; like_count: number }>>({ url: '/api/article/like', method: 'POST', data: toUrlEncoded({ article_id }) }),
  favoriteArticle: (article_id: number) => request<Result<{ favorited: boolean; favorite_count: number }>>({ url: '/api/article/favorite', method: 'POST', data: toUrlEncoded({ article_id }) }),
  likeComment: (comment_id: number) => request<Result<{ liked: boolean; like_count: number }>>({ url: '/api/comment/like', method: 'POST', data: toUrlEncoded({ comment_id }) }),
}

export const userApi = {
  login: (data: LoginForm) => request<Result<UserLoginResponse>>({ url: '/api/user/login', method: 'POST', data: toUrlEncoded(data) }),
  register: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/register', method: 'POST', data: toUrlEncoded(data) }),
  getUserInfo: () => request<Result<User>>({ url: '/api/user/getUser', method: 'GET' }),
  updateUserInfo: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/update', method: 'POST', data: toUrlEncoded(data) }),
  updateEmail: (data: { email: string; code: string; new_email: string }) => request<Result>({ url: '/api/user/update/email', method: 'POST', data: toUrlEncoded(data) }),
  updatePassword: (data: { username: string; old_pwd: string; new_pwd: string }) => request<Result>({ url: '/api/user/updatePwd', method: 'POST', data: toUrlEncoded(data) }),
  updateEmailPassword: (data: { email: string; code: string; new_pwd: string }) => request<Result>({ url: '/api/user/UpdateEmailPwd', method: 'POST', data: toUrlEncoded(data) }),
  createRecharge: (data: { amount: number; pay_way: 'alipay' | 'wxpay' }) => request<Result>({ url: '/api/user/recharge/create', method: 'POST', data: toUrlEncoded(data) }),
  getOrders: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/user/pay/order/list', method: 'GET', params }),
  getRoleDiscounts: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/user/role/discount/list', method: 'GET', params }),
  getRealNameInfo: () => request<Result>({ url: '/api/user/realname/info', method: 'GET' }),
  verifyRealName: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/alipay/realname/verify', method: 'POST', data: toUrlEncoded(data) }),
  applyPromotion: () => request<Result>({ url: '/api/user/promotion/apply', method: 'POST' }),
  getPromotionStatus: () => request<Result>({ url: '/api/user/promotion/status', method: 'GET' }),
  getPromotionStats: () => request<Result>({ url: '/api/user/promotion/stats', method: 'GET' }),
  getInvitees: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/user/promotion/inviteeList', method: 'GET', params }),
  getCommissions: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/user/commission/list', method: 'GET', params }),
  getWithdrawals: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/user/withdrawal/list', method: 'GET', params }),
  applyWithdrawal: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/withdrawal/apply', method: 'POST', data: toUrlEncoded(data) }),
  upload: (data: FormData) => request<Result<string>>({ url: '/api/user/upload', method: 'POST', data }),
  getComments: (params?: Record<string, unknown>) => request<Result<PageResponse<Comment>>>({ url: '/api/user/GetCommentInfo', method: 'GET', params }),
  createComment: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/CreateComment', method: 'POST', data: toUrlEncoded(data) }),
  getAppCategories: () => request<Result<AppCategory[]>>({ url: '/api/user/app/category/list', method: 'GET' }),
  getApps: (params?: Record<string, unknown>) => request<Result<App[]>>({ url: '/api/user/app/list', method: 'GET', params }),
  getAppDetail: (id: number) => request<Result<App>>({ url: '/api/user/app/detail', method: 'GET', params: { id } }),
  getAppPlans: (app_id: number) => request<Result<AppPlan[]>>({ url: '/api/user/app/plan/list', method: 'GET', params: { app_id } }),
  getAppEndpoints: (app_id: number) => request<Result<AppEndpoint[]>>({ url: '/api/user/app/endpoint/list', method: 'GET', params: { app_id } }),
  createAppOrder: (data: { app_id: number; plan_id: number; pay_way: 'alipay' | 'wxpay' }) => request<Result>({ url: '/api/user/app/order/create', method: 'POST', data: toUrlEncoded(data) }),
  getAppOrders: () => request<Result<AppOrder[]>>({ url: '/api/user/app/order/list', method: 'GET' }),
  getSubscriptions: () => request<Result<AppSubscription[]>>({ url: '/api/user/app/subscription/list', method: 'GET' }),
  getAppRealNameRecords: (params?: Record<string, unknown>) => request<Result<PageResponse<AppRealNameRecord>>>({ url: '/api/user/app/realname/record/list', method: 'GET', params }),
  getSubscriptionSecret: (id: number) => request<Result<{ app_key: string; app_secret: string }>>({ url: '/api/user/app/subscription/secret', method: 'GET', params: { id } }),
  getTagList: (params?: Record<string, unknown>) => request<Result<Tag[]>>({ url: '/api/user/GetTagList', method: 'GET', params }),
  getMyArticles: (params?: Record<string, unknown>) => request<Result<PageResponse<Article>>>({ url: '/api/user/GetArticleInfo', method: 'GET', params }),
  createArticle: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/CreateArticle', method: 'POST', data: toUrlEncoded(data) }),
  updateArticle: (data: Record<string, unknown>) => request<Result>({ url: '/api/user/UpdateArticle', method: 'POST', data: toUrlEncoded(data) }),
  deleteArticle: (id: number) => request<Result>({ url: '/api/user/DeleteArticle', method: 'PUT', params: { id } }),
  getUserCategoryTree: () => request<Result<Category[]>>({ url: '/api/user/GetCategoryChildrenInfo', method: 'GET' }),
  debugApp: (data: { app_id: number; endpoint_id: number; body: string }) => request<Result>({ url: '/api/user/app/debug', method: 'POST', data: toUrlEncoded(data) }),
  purchaseArticle: (article_id: number, pay_way: 'balance' | 'alipay' | 'wxpay' = 'balance') => request<Result>({ url: '/api/user/article/purchase', method: 'POST', data: toUrlEncoded({ article_id, pay_way }) }),
}

export const adminApi = {
  login: (data: LoginForm) => request<Result<{ token: string }>>({ url: '/api/admin/login', method: 'POST', data: toUrlEncoded(data) }),
  getAdminInfo: () => request<Result<AdminInfo>>({ url: '/api/admin/getAdminInfo', method: 'GET' }),
  updateAdminInfo: (data: Record<string, unknown>) => request<Result<AdminInfo & { token?: string }>>({ url: '/api/admin/update', method: 'POST', data: toUrlEncoded(data) }),
  updateAdminPassword: (data: { username: string; old_pwd: string; new_pwd: string }) => request<Result>({ url: '/api/admin/updateAdminPwd', method: 'POST', data: toUrlEncoded(data) }),
  getUserList: (params?: Record<string, unknown>) => request<Result<PageResponse<User>>>({ url: '/api/admin/GetUserInfo', method: 'GET', params }),
  createUser: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/CreateUser', method: 'POST', data: toUrlEncoded(data) }),
  updateUser: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/UpdateUser', method: 'POST', data: toUrlEncoded(data) }),
  deleteUser: (id: number) => request<Result>({ url: '/api/admin/DeleteUser', method: 'PUT', data: toUrlEncoded({ id }) }),
  getUserStat: () => request<Result>({ url: '/api/admin/user/stat', method: 'GET' }),
  getDashboardStat: () => request<Result>({ url: '/api/admin/dashboard/stat', method: 'GET' }),
  getProvinceAccess: (params?: Record<string, unknown>) => request<Result>({ url: '/api/GetProvinceAccess', method: 'GET', params }),
  getTagSearch: (params?: Record<string, unknown>) => request<Result>({ url: '/api/GetTagSearch', method: 'GET', params }),
  updateRegisterConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/register/update', method: 'POST', data: toUrlEncoded(data) }),
  getRoleDiscounts: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/role/discount/list', method: 'GET', params }),
  updateRoleDiscount: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/role/discount/update', method: 'POST', data: toUrlEncoded(data) }),
  getPaymentConfigs: () => request<Result<PaymentConfig[]>>({ url: '/api/admin/payment/config/list', method: 'GET' }),
  updatePaymentConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/payment/config/update', method: 'POST', data: toUrlEncoded(data) }),
  getAlipayConfig: () => request<Result>({ url: '/api/admin/alipay/info', method: 'GET' }),
  updateAlipayConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/alipay/update', method: 'POST', data: toUrlEncoded(data) }),
  getRealNameConfig: () => request<Result<RealNameConfig>>({ url: '/api/admin/realname/config', method: 'GET' }),
  updateRealNameConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/realname/config/update', method: 'POST', data: toUrlEncoded(data) }),
  getRechargeOrders: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/recharge/order', method: 'GET', params }),
  getPayOrders: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/pay/order/list', method: 'GET', params }),
  getPromotionConfig: () => request<Result>({ url: '/api/admin/promotion/config', method: 'GET' }),
  updatePromotionConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/promotion/config', method: 'POST', data: toUrlEncoded(data) }),
  getPromotionUsers: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/promotion/userList', method: 'GET', params }),
  getInviteRelations: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/promotion/inviteList', method: 'GET', params }),
  getCommissions: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/promotion/commissionList', method: 'GET', params }),
  getWithdrawals: (params?: Record<string, unknown>) => request<Result<PageResponse>>({ url: '/api/admin/withdrawal/list', method: 'GET', params }),
  reviewWithdrawal: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/withdrawal/review', method: 'POST', data: toUrlEncoded(data) }),
  getEmailInfo: () => request<Result<EmailConfig>>({ url: '/api/admin/getEmailInfo', method: 'GET' }),
  updateEmail: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/UpdateEmail', method: 'POST', data: toUrlEncoded(data) }),
  updateSiteConfig: (data: object) => request<Result<SiteConfig>>({ url: '/api/admin/updateSiteConfig', method: 'POST', data: toUrlEncoded(data) }),
  getCarousels: () => request<Result<CarouselConfig[]>>({ url: '/api/admin/carousel/list', method: 'GET' }),
  updateCarousel: (data: Partial<CarouselConfig> & { id: number }) => request<Result<CarouselConfig>>({ url: '/api/admin/carousel/update', method: 'POST', data }),
  getAppCategories: () => request<Result<AppCategory[]>>({ url: '/api/admin/app/category/list', method: 'GET' }),
  saveAppCategory: (data: Partial<AppCategory>) => request<Result<AppCategory>>({ url: '/api/admin/app/category/save', method: 'POST', data: toUrlEncoded(data) }),
  deleteAppCategory: (id: number) => request<Result>({ url: '/api/admin/app/category/delete', method: 'DELETE', params: { id } }),
  getApps: () => request<Result<App[]>>({ url: '/api/admin/app/list', method: 'GET' }),
  getAppDetail: (id: number) => request<Result<App>>({ url: '/api/admin/app/detail', method: 'GET', params: { id } }),
  saveApp: (data: Partial<App>) => request<Result<App>>({ url: '/api/admin/app/save', method: 'POST', data: toUrlEncoded(data) }),
  deleteApp: (id: number) => request<Result>({ url: '/api/admin/app/delete', method: 'DELETE', params: { id } }),
  getAppPlans: (app_id: number) => request<Result<AppPlan[]>>({ url: '/api/admin/app/plan/list', method: 'GET', params: { app_id } }),
  saveAppPlan: (data: Partial<AppPlan>) => request<Result<AppPlan>>({ url: '/api/admin/app/plan/save', method: 'POST', data: toUrlEncoded(data) }),
  deleteAppPlan: (id: number) => request<Result>({ url: '/api/admin/app/plan/delete', method: 'DELETE', params: { id } }),
  getAppEndpoints: (app_id: number) => request<Result<AppEndpoint[]>>({ url: '/api/admin/app/endpoint/list', method: 'GET', params: { app_id } }),
  saveAppEndpoint: (data: Partial<AppEndpoint>) => request<Result<AppEndpoint>>({ url: '/api/admin/app/endpoint/save', method: 'POST', data: toUrlEncoded(data) }),
  deleteAppEndpoint: (id: number) => request<Result>({ url: '/api/admin/app/endpoint/delete', method: 'DELETE', params: { id } }),
  getAppOrders: (params?: Record<string, unknown>) => request<Result<AppOrder[]>>({ url: '/api/admin/app/order/list', method: 'GET', params }),
  getAppSubscriptions: (params?: Record<string, unknown>) => request<Result<AppSubscription[]>>({ url: '/api/admin/app/subscription/list', method: 'GET', params }),
  getAppRealNameRecords: (params?: Record<string, unknown>) => request<Result<PageResponse<AppRealNameRecord>>>({ url: '/api/admin/app/realname/record/list', method: 'GET', params }),
  upload: (data: FormData) => request<Result<string>>({ url: '/api/admin/upload', method: 'POST', data }),
  getSmsConfig: () => request<Result<Record<string, unknown>>>({ url: '/api/admin/sms/config', method: 'GET' }),
  updateSmsConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/sms/config/update', method: 'POST', data: toUrlEncoded(data) }),
  testSms: (data: { phone: string }) => request<Result<boolean>>({ url: '/api/admin/sms/test', method: 'POST', data: toUrlEncoded(data) }),
  getAntiBrushConfig: () => request<Result<Record<string, unknown>>>({ url: '/api/admin/anti-brush/config', method: 'GET' }),
  updateAntiBrushConfig: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/anti-brush/config/update', method: 'POST', data: toUrlEncoded(data) }),
  getAdminCategoryTree: () => request<Result<Category[]>>({ url: '/api/admin/GetCategoryChildrenInfo', method: 'GET' }),
  getTagList: (params?: Record<string, unknown>) => request<Result>({ url: '/api/admin/GetTagList', method: 'GET', params }),
  createAdminCategory: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/CreateCategory', method: 'POST', data: toUrlEncoded(data) }),
  updateAdminCategory: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/UpdateCategory', method: 'POST', data: toUrlEncoded(data) }),
  deleteAdminCategory: (cid: number) => request<Result>({ url: '/api/admin/DeleteCategory', method: 'PUT', data: toUrlEncoded({ cid }) }),
  getAdminArticles: (params?: Record<string, unknown>) => request<Result<PageResponse<Article>>>({ url: '/api/admin/GetArticleInfo', method: 'GET', params }),
  createAdminArticle: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/CreateArticle', method: 'POST', data: toUrlEncoded(data) }),
  updateAdminArticle: (data: Record<string, unknown>) => request<Result>({ url: '/api/admin/UpdateArticle', method: 'POST', data: toUrlEncoded(data) }),
  getAdminComments: (params?: Record<string, unknown>) => request<Result<PageResponse<Comment>>>({ url: '/api/admin/GetCommentInfo', method: 'GET', params }),
  updateAdminComment: (data: { id: number; status: number }) => request<Result>({ url: '/api/admin/UpdateComment', method: 'POST', data: toUrlEncoded(data) }),
  deleteAdminComment: (id: number) => request<Result>({ url: '/api/admin/DeleteComment', method: 'PUT', data: toUrlEncoded({ id }) }),
  deleteAdminArticle: (id: number) => request<Result>({ url: '/api/admin/DeleteArticle', method: 'PUT', params: { id } }),
}


